# Generated by Django 3.1.2 on 2022-02-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
